/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author Kudry
 */
public class VentanaInternaVideo extends VentanaInterna {

    
    private EmbeddedMediaPlayer vlcPlayer = null;
    private File fMedia;

//  private Player player = null;

    /**
     * Creates new form VentanaInternaVideo
     */
    private VentanaInternaVideo(int x, int y, File f) {
        super(x,y,null,null);
        
        File file = new File(f.getAbsolutePath()){
            @Override
            public String toString(){
                return this.getName();
            }
        };
        
        setTitle(file.toString());
              
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        aVisual.setPreferredSize(new Dimension(300,300));
        add(aVisual,java.awt.BorderLayout.CENTER);
        vlcPlayer = aVisual.getMediaPlayer();
        vlcPlayer.addMediaPlayerEventListener(new VideoListener());
        
        initComponents();
        
        botonVideoPause.setEnabled(false);
        botonVideoStop.setEnabled(false);
    }
    
    /**
     * Crea una ventana de video en una posicion dada abriendo el fichero
     * proporcionado
     * @param x
     * @param y
     * @param f
     * @return 
     */
    public static VentanaInternaVideo getInstance(int x, int y, File f){
        VentanaInternaVideo v = new VentanaInternaVideo(x,y,f);
        return (v.vlcPlayer!=null?v:null);
    }
    
    /**
     * Reproduce el video
     */
    public void play(){
        
        if(vlcPlayer != null){
            
            if(vlcPlayer.isPlayable()){
                vlcPlayer.play();
            }else{
                vlcPlayer.playMedia(fMedia.getAbsolutePath());
            }

            botonVideoPlay.setEnabled(false);
            botonVideoPause.setEnabled(true);
            botonVideoStop.setEnabled(true);
        }

    }

    /**
     * Pausa el video
     */
    public void pause(){
        
        if(vlcPlayer != null && vlcPlayer.isPlaying()){
            vlcPlayer.pause();
            botonVideoPlay.setEnabled(true);
            botonVideoPause.setEnabled(false);
            botonVideoStop.setEnabled(true);
        }
        
    }
    
    /**
     * Para el video
     */
    public void stop(){
        
        if(vlcPlayer != null){
            vlcPlayer.stop();
            botonVideoPlay.setEnabled(true);
            botonVideoPause.setEnabled(false);
            botonVideoStop.setEnabled(false);
        }
        
    }
    
    /**
     * Devuelve una captura del video 
     * @return 
     */
    @Override
    public BufferedImage getScreenShot(){
        return vlcPlayer.getVideoSurfaceContents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVideoControles = new javax.swing.JPanel();
        botonVideoPlay = new javax.swing.JButton();
        botonVideoPause = new javax.swing.JButton();
        botonVideoStop = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonVideoPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/res/iconosPracticaVideo/Play.png"))); // NOI18N
        botonVideoPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVideoPlayActionPerformed(evt);
            }
        });
        panelVideoControles.add(botonVideoPlay);

        botonVideoPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/res/iconosPracticaVideo/Pausa.png"))); // NOI18N
        botonVideoPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVideoPauseActionPerformed(evt);
            }
        });
        panelVideoControles.add(botonVideoPause);

        botonVideoStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/res/iconosPracticaVideo/Stop.png"))); // NOI18N
        botonVideoStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVideoStopActionPerformed(evt);
            }
        });
        panelVideoControles.add(botonVideoStop);

        getContentPane().add(panelVideoControles, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVideoPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVideoPauseActionPerformed
        pause();
    }//GEN-LAST:event_botonVideoPauseActionPerformed

    private void botonVideoPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVideoPlayActionPerformed
        play();
    }//GEN-LAST:event_botonVideoPlayActionPerformed

    private void botonVideoStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVideoStopActionPerformed
        stop();
    }//GEN-LAST:event_botonVideoStopActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        stop();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVideoPause;
    private javax.swing.JButton botonVideoPlay;
    private javax.swing.JButton botonVideoStop;
    private javax.swing.JPanel panelVideoControles;
    // End of variables declaration//GEN-END:variables
}
