/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import sm.ko.ui.Lienzo2DImagen;


/**
 *
 * @author Kudry
 */
public class VentanaInternaImagen extends VentanaInterna {

    /**
     * Creates new form VentanaInternaImagen
     */
    public VentanaInternaImagen(int x, int y, String title, Frame FRAME) {
        super(x,y,title,FRAME);
        this.setPreferredSize(new Dimension(300,300));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lienzo2DImagen1 = new sm.ko.ui.Lienzo2DImagen();

        javax.swing.GroupLayout lienzo2DImagen1Layout = new javax.swing.GroupLayout(lienzo2DImagen1);
        lienzo2DImagen1.setLayout(lienzo2DImagen1Layout);
        lienzo2DImagen1Layout.setHorizontalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        lienzo2DImagen1Layout.setVerticalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(lienzo2DImagen1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private sm.ko.ui.Lienzo2DImagen lienzo2DImagen1;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el lienzo que almacena la ventana interna imagen
     * @return 
     */
    @Override
    public Lienzo2DImagen getLienzo(){
        return lienzo2DImagen1;
    }
    
    /**
     * Devuelve una copia de la imagen contenida en la ventrana interna 
     * pasada como argumento
     * @param vi 
     */
    public void duplicarImagen(VentanaInterna vi){
        ColorModel cm = vi.getLienzo().getImage().getColorModel();
        WritableRaster raster = vi.getLienzo().getImage().copyData(null);
        lienzo2DImagen1.setImage(new BufferedImage(cm, raster, cm.isAlphaPremultiplied(), null));
        
        setTitle(vi.getTitle()+" copia");
    }

}
